#!/bin/sh

docker run -d -p 514:514 -p 514:514/udp -v `pwd`/logs:/var/log green/greenfx-log
sleep 2

# Fuse requires a tty or else it exits right away...
docker run -t -d -p 61616:61616 -p 8161:8161 -p 8181:8181 green/greenfx-fuse

docker run -d -p 8083:8083 -p 8086:8086 green/greenfx-db-ticks
docker run -d -p 5432:5432 green/greenfx-db
docker run -d green/greenfx-ticks-oanda

echo A-MQ web interface:  http://localhost:8181/activemqweb
echo InfluxDB web interface:  http://localhost:8083
echo View container logs:  tail -f logs/*
